# NAN 찾기

In [1]:
import numpy as np

In [2]:
data = [2,2,2]
np.isfinite(data)

array([ True,  True,  True])

In [3]:
data = np.array([2,2,np.nan])
np.isinf(data)

array([False, False, False])

In [4]:
mask_data = np.array([1, 1], dtype=bool)
mask_data
#print(data[mask_data])

array([ True,  True])

# 최대값 찾기

In [5]:
data_set = np.array([
    [1,2,3,4],
    [1,2,3,5],
    [1,2,3,6]
])

In [6]:
np.nanargmax(data_set)

11

In [7]:
a = np.array([[np.nan, 4], [2, 10]])
#print(np.argmax(a))
#print(np.nanargmax(a))
#np.nanargmax(a, axis=0)
#np.nanargmax(a, axis=1)
x = np.isfinite(a)
a[~x] =100

# 테이블 설정

In [14]:
import numpy as np

color = np.random.randint(1,5, size=(1, 10))
test_data = np.random.randint(1,10, size=(1,10))

print("data\n",
      test_data)

print("color data \n",
      color)
print("color shape : ", color.shape)
print("teat_data shape : ", test_data.shape)
c = color[:, test_data]
print("c shape : ", c.shape)
print("결과 \n",c)


data
 [[7 2 2 5 8 8 2 8 5 5]]
color data 
 [[1 2 1 4 2 4 4 1 3 4]]
color shape :  (1, 10)
teat_data shape :  (1, 10)
c shape :  (1, 1, 10)
결과 
 [[[1 1 1 4 3 3 1 3 4 4]]]


In [17]:
print(test_data)
test_data[0][6] = 3
print(test_data)
c = color[:, test_data]
c

[[7 2 2 5 8 8 7 8 5 5]]
[[7 2 2 5 8 8 3 8 5 5]]


array([[[1, 1, 1, 4, 3, 3, 4, 3, 4, 4]]])

In [18]:
test_data

array([[7, 2, 2, 5, 8, 8, 3, 8, 5, 5]])

In [ ]:
color[0][1] = 3
print(color)
color[:, test_data]

In [59]:
import cv2
import numpy as np

# 이미지 읽기
img = cv2.imread('hw1/rubik/indoor.png', cv2.IMREAD_GRAYSCALE)
img = cv2.resize(img, (512,512))
print(img.shape)
print(type(img[0][0]))
# Look-Up Table 생성 (명암 대비 조절)
lut = np.arange(0, 256, 1, dtype=np.uint8).reshape(1, -1)

lut = 2 * lut  # 각 픽셀 값을 2배로 증가
print(lut.shape)
print(img.max())

# LUT 적용
print(img)
print()
result_img = cv2.LUT(src=img, lut=lut)
# result_img = lut[:, img]
print(result_img)

# 결과 이미지 저장
#cv2.imshow('output_image.jpg', result_img)

(512, 512)
<class 'numpy.uint8'>
(1, 256)
255
[[255 255 255 ... 255 255 255]
 [255 243 220 ... 246 252 255]
 [255 220 150 ... 228 246 255]
 ...
 [255 231 182 ... 186 232 255]
 [255 247 231 ... 232 247 255]
 [255 255 255 ... 255 255 255]]

[[254 254 254 ... 254 254 254]
 [254 230 184 ... 236 248 254]
 [254 184  44 ... 200 236 254]
 ...
 [254 206 108 ... 116 208 254]
 [254 238 206 ... 208 238 254]
 [254 254 254 ... 254 254 254]]


In [41]:
print(type(img))

255* 2

<class 'numpy.ndarray'>


510

In [24]:
510 // 256

1

# 2차원 3차원으로 합치기

In [4]:
import numpy as np
a = np.array([
    [1,2,3],
    [3,4,4]
])
c = [a, a]

In [5]:
np.stack(c, axis=2).shape

(2, 3, 2)

In [7]:
np.stack(c, axis=2)

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[3, 3],
        [4, 4],
        [4, 4]]])

In [1]:
import numpy as np


In [15]:
palette = np.array([1,0]).reshape(-1,1)
palette

array([[1],
       [0]])

In [16]:
value = np.arange(0, 9).reshape(1, -1)
value

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [18]:
np.abs(palette - value)

array([[1, 0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [30]:
lut = np.arange(0, 256, 1, dtype=np.uint8).reshape(1, -1) * 2
lut.shape

(1, 256)

In [34]:
lut[:, 255]
lut[:, 255]

array([254], dtype=uint8)

In [7]:
import scipy
import cv2
import numpy as np
import matplotlib.pyplot as plt
import math
def genGausKernel1D(width, sigma):
    arr = np.arange((width//2)*(-1), (width//2)+1)
    #중심에서부터의 거리를 계산함,
    print(arr)
    arr = np.array([float(x) for x in arr])
    #float 처리를 해주지 않으면 값이 달라질 수 있어서 처리해주었다
    kernel_1d= np.exp((-arr*arr)/(2*sigma**2))
    #위에서 봤던 수식을 그대로 적용했다. 달라진 점은, 앞에 상수로 나눠주는 부분을 생략한건데
    #어차피 나중에 커널 전체 값의 합을 1로 만들기 위해서 커널 전체의 합으로 나눠주기 때문에
    #상수부분이 필요 없다고 생각해서 나누지 않았다
    kernel_1d /= np.sqrt(np.pi * 2) * sigma
    #kernel은 모든 element의 합이 1이어야하기 때문에 전체 수의 합으로 나눠준다.
    #비율이 중요하다는 뜻으로 해석했다.
    return np.array([kernel_1d])

In [8]:
genGausKernel1D(5,3)

[-2 -1  0  1  2]


array([[0.10648267, 0.12579441, 0.13298076, 0.12579441, 0.10648267]])

In [ ]:
def genGaussianKernel(width, sigma):
    array = np.arange((width//2)*(-1), (width//2)+1)
    #중심에서부터의 거리 계산
    arr = np.zeros((width, width))
    #x^2+y^2 부분을 미리 계산해둘 매트릭스 initialize
    for x in range(width):
        for y in range(width):
            arr[x,y] = array[x]**2+array[y]**2
            #중심에서부터의 거리를 제곱합으로 계산
    kernel_2d = np.zeros((width, width))
    #커널의 값을 저장할 매트릭스 생성
    for x in range(width):
        for y in range(width):
             kernel_2d[x,y] = np.exp(-arr[x,y]/(2*sigma**2))
             #수식에 맞게 값 저장(역시나 상수 부분은 생략)
    kernel_2d /= kernel_2d.sum()
    #전체 값의 합으로 나누어 필터 전체의 합이 1이 되도록 함
    return kernel_2d