# NAN 찾기

In [1]:
import numpy as np

In [2]:
data = [2,2,2]
np.isfinite(data)

array([ True,  True,  True])

In [3]:
data = np.array([2,2,np.nan])
np.isinf(data)

array([False, False, False])

In [4]:
mask_data = np.array([1, 1], dtype=bool)
mask_data
#print(data[mask_data])

array([ True,  True])

# 최대값 찾기

In [5]:
data_set = np.array([
    [1,2,3,4],
    [1,2,3,5],
    [1,2,3,6]
])

In [6]:
np.nanargmax(data_set)

11

In [7]:
a = np.array([[np.nan, 4], [2, 10]])
#print(np.argmax(a))
#print(np.nanargmax(a))
#np.nanargmax(a, axis=0)
#np.nanargmax(a, axis=1)
x = np.isfinite(a)
a[~x] =100

# 테이블 설정

In [14]:
import numpy as np

color = np.random.randint(1,5, size=(1, 10))
test_data = np.random.randint(1,10, size=(1,10))

print("data\n",
      test_data)

print("color data \n",
      color)
print("color shape : ", color.shape)
print("teat_data shape : ", test_data.shape)
c = color[:, test_data]
print("c shape : ", c.shape)
print("결과 \n",c)


data
 [[7 2 2 5 8 8 2 8 5 5]]
color data 
 [[1 2 1 4 2 4 4 1 3 4]]
color shape :  (1, 10)
teat_data shape :  (1, 10)
c shape :  (1, 1, 10)
결과 
 [[[1 1 1 4 3 3 1 3 4 4]]]


In [17]:
print(test_data)
test_data[0][6] = 3
print(test_data)
c = color[:, test_data]
c

[[7 2 2 5 8 8 7 8 5 5]]
[[7 2 2 5 8 8 3 8 5 5]]


array([[[1, 1, 1, 4, 3, 3, 4, 3, 4, 4]]])

In [18]:
test_data

array([[7, 2, 2, 5, 8, 8, 3, 8, 5, 5]])

In [ ]:
color[0][1] = 3
print(color)
color[:, test_data]

In [59]:
import cv2
import numpy as np

# 이미지 읽기
img = cv2.imread('hw1/rubik/indoor.png', cv2.IMREAD_GRAYSCALE)
img = cv2.resize(img, (512,512))
print(img.shape)
print(type(img[0][0]))
# Look-Up Table 생성 (명암 대비 조절)
lut = np.arange(0, 256, 1, dtype=np.uint8).reshape(1, -1)

lut = 2 * lut  # 각 픽셀 값을 2배로 증가
print(lut.shape)
print(img.max())

# LUT 적용
print(img)
print()
result_img = cv2.LUT(src=img, lut=lut)
# result_img = lut[:, img]
print(result_img)

# 결과 이미지 저장
#cv2.imshow('output_image.jpg', result_img)

(512, 512)
<class 'numpy.uint8'>
(1, 256)
255
[[255 255 255 ... 255 255 255]
 [255 243 220 ... 246 252 255]
 [255 220 150 ... 228 246 255]
 ...
 [255 231 182 ... 186 232 255]
 [255 247 231 ... 232 247 255]
 [255 255 255 ... 255 255 255]]

[[254 254 254 ... 254 254 254]
 [254 230 184 ... 236 248 254]
 [254 184  44 ... 200 236 254]
 ...
 [254 206 108 ... 116 208 254]
 [254 238 206 ... 208 238 254]
 [254 254 254 ... 254 254 254]]


In [41]:
print(type(img))

255* 2

<class 'numpy.ndarray'>


510

In [24]:
510 // 256

1

# 2차원 3차원으로 합치기

In [4]:
import numpy as np
a = np.array([
    [1,2,3],
    [3,4,4]
])
c = [a, a]

In [5]:
np.stack(c, axis=2).shape

(2, 3, 2)

In [7]:
np.stack(c, axis=2)

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[3, 3],
        [4, 4],
        [4, 4]]])

In [1]:
import numpy as np


In [15]:
palette = np.array([1,0]).reshape(-1,1)
palette

array([[1],
       [0]])

In [16]:
value = np.arange(0, 9).reshape(1, -1)
value

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [18]:
np.abs(palette - value)

array([[1, 0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7, 8]])