In [1]:
import cv2
import numpy as np

path = 'indoor.png'

a = cv2.imread(path)

(256, 256, 3)

In [6]:
a_trans = np.transpose(a, (2, 1, 0))
a_trans.shape

(3, 256, 256)

In [3]:
a = np.arange(start=1, stop=10, step=1).reshape(3 ,3)

In [4]:
print(a)
a * a * a

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[  1,   8,  27],
       [ 64, 125, 216],
       [343, 512, 729]])

In [7]:
import numpy as np
import cv2
# 1. RGB 컬러 배열 확인
rgb_colors = np.array([[256, 3, 0], [0, 256, 3], [0, 3, 256]], dtype=np.uint8)


data = np.load("../visualize/mysterydata/mysterydata4.npy").astype(np.uint8)
channels = cv2.split(data)
image = channels[0]

# 2. 512x512 이미지 배열 확인
#image = np.array(..., dtype=np.uint8)  # ... 에는 이미지 데이터를 넣어주세요.

# 3. 이미지 크기 확인
height, width = image.shape
print(height)
print(width)

# 4. 빈 RGB 이미지 생성
rgb_image = np.zeros((height, width, 3), dtype=np.uint8)

# 5. 각 픽셀에 RGB 컬러 매핑
for i in range(height):
    for j in range(width):
        rgb_image[i, j] = rgb_colors[image[i, j]]

# 6. 결과 확인
print(rgb_image)

# 7. (옵션) 이미지 저장
# cv2 라이브러리를 사용하여 이미지를 저장할 수 있습니다.
import cv2
cv2.imwrite("rgb_image.png", rgb_image)

512
512


IndexError: index 3 is out of bounds for axis 0 with size 3