In [1]:
import cv2
import numpy as np

path = 'indoor.png'

a = cv2.imread(path)

In [2]:
a_trans = np.transpose(a, (2, 1, 0))

In [3]:
a = np.arange(start=1, stop=10, step=1).reshape(3 ,3)

In [4]:
print(a)
a * a * a

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[  1,   8,  27],
       [ 64, 125, 216],
       [343, 512, 729]])